package com.giut0;

import java.nio.file.FileAlreadyExistsException;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Giut0
 */
public class MainJFrameWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrameWindow
     */
    public MainJFrameWindow() {
        initComponents();
        setLocationRelativeTo(null);
        jProgressBar1.setStringPainted(true);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldFile = new javax.swing.JTextField();
        jButtonSelectFile = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldDest = new javax.swing.JTextField();
        jButtonSelectDest = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldGameName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldGameCode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButtonStart = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaLogs = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wii game loader");

        jTextFieldFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFileActionPerformed(evt);
            }
        });

        jButtonSelectFile.setText("Select file");
        jButtonSelectFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectFileActionPerformed(evt);
            }
        });

        jLabel1.setText("File [wbfs]");

        jTextFieldDest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDestActionPerformed(evt);
            }
        });

        jButtonSelectDest.setText("Select file");
        jButtonSelectDest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectDestActionPerformed(evt);
            }
        });

        jLabel2.setText("Destination drive");

        jTextFieldGameName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGameNameActionPerformed(evt);
            }
        });

        jLabel3.setText("Game name");

        jTextFieldGameCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGameCodeActionPerformed(evt);
            }
        });

        jLabel4.setText("Game code");

        jButtonStart.setText("Start");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        jProgressBar1.setForeground(new java.awt.Color(0, 204, 102));

        jTextAreaLogs.setEditable(false);
        jTextAreaLogs.setColumns(20);
        jTextAreaLogs.setRows(5);
        jScrollPane1.setViewportView(jTextAreaLogs);

        jLabel5.setText("Logs");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldDest, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSelectDest))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldGameCode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                        .addComponent(jTextFieldGameName, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldFile, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSelectFile))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSelectFile))
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSelectDest))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldGameName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldGameCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFileActionPerformed

    private void jTextFieldDestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDestActionPerformed

    private void jTextFieldGameNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGameNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGameNameActionPerformed

    private void jTextFieldGameCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGameCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGameCodeActionPerformed

    private void jButtonSelectFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectFileActionPerformed
        JFileChooser jFileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("wbfs files", "wbfs");
        jFileChooser.setFileFilter(filter);
        jFileChooser.showOpenDialog(null);

        String fileString = jFileChooser.getSelectedFile().toPath().toString();
        jTextFieldFile.setText(fileString);
    }//GEN-LAST:event_jButtonSelectFileActionPerformed

    private void jButtonSelectDestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectDestActionPerformed
        JFileChooser jDirChooser = new JFileChooser();
        jDirChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jDirChooser.setAcceptAllFileFilterUsed(false);
        jDirChooser.showOpenDialog(null);

        String dirString = jDirChooser.getSelectedFile().toPath().toString() + "/";
        jTextFieldDest.setText(dirString);

    }//GEN-LAST:event_jButtonSelectDestActionPerformed

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed

        boolean value = false; // Initializing a boolean variable

        // Setting initial values for progress bar and text area
        jProgressBar1.setValue(0);
        jTextAreaLogs.setText(null);

        try {
            // Checking for empty fields in the input text fields
            WiiGameException.checkEmptyFields(jTextFieldFile.getText(), jTextFieldDest.getText(), jTextFieldGameName.getText(), jTextFieldGameCode.getText());

            // Setting progress bar value and updating logs
            jProgressBar1.setValue(10);
            jTextAreaLogs.append(">> Starting progress..." + "\n");

            // Calling the transferFile method from Main class to transfer Wii game files
            value = Main.transferFile(jTextFieldFile.getText(), jTextFieldDest.getText(), jTextFieldGameName.getText(), jTextFieldGameCode.getText());

            // Handling the result of the file transfer
            if (value == true) {
                jTextAreaLogs.append(">> Completed!" + "\n");
                jProgressBar1.setValue(100);
            } else {
                jTextAreaLogs.append(">> Process failed!" + "\n");
                jProgressBar1.setValue(0);
            }
        } catch (FileAlreadyExistsException f) {
            // Handling the case where the file already exists
            jTextAreaLogs.append(">> Error: File already exists \n");
            jProgressBar1.setValue(0);
            System.out.println(f);
        } catch (Exception e) {
            // Handling other exceptions and displaying their messages
            jTextAreaLogs.append(e.getMessage().toString() + "\n");
            jProgressBar1.setValue(0);
            System.out.println(e);
        }

    }//GEN-LAST:event_jButtonStartActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSelectDest;
    private javax.swing.JButton jButtonSelectFile;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextAreaLogs;
    private javax.swing.JTextField jTextFieldDest;
    private javax.swing.JTextField jTextFieldFile;
    private javax.swing.JTextField jTextFieldGameCode;
    private javax.swing.JTextField jTextFieldGameName;
    // End of variables declaration//GEN-END:variables
}
